# Generated by Django 5.2.10 on 2026-02-02 02:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("article_view", "Article View"),
                            ("article_purchase", "Article Purchase"),
                            ("subscription_started", "Subscription Started"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            ("appointment_booked", "Appointment Booked"),
                            ("newsletter_subscribed", "Newsletter Subscribed"),
                            ("newsletter_unsubscribed", "Newsletter Unsubscribed"),
                        ],
                        db_index=True,
                        help_text="Type of event",
                        max_length=40,
                        verbose_name="event type",
                    ),
                ),
                (
                    "anonymous_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Anonymous visitor ID",
                        max_length=120,
                        verbose_name="anonymous ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL path where event occurred",
                        max_length=512,
                        verbose_name="path",
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTTP referrer URL",
                        max_length=512,
                        verbose_name="referrer",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Browser user agent string",
                        max_length=512,
                        verbose_name="user agent",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hashed IP address for privacy",
                        max_length=128,
                        verbose_name="IP hash",
                    ),
                ),
                (
                    "metadata_json",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional event data in JSON format",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated user (if authenticated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_e_event_t_ef40a5_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_e_user_id_9a87e5_idx",
                    ),
                ],
            },
        ),
    ]
