# Generated by Django 5.2.10 on 2026-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page View"),
                    ("article_view", "Article View"),
                    ("article_read", "Article Read"),
                    ("article_purchase", "Article Purchase"),
                    ("subscription_started", "Subscription Started"),
                    ("subscription_cancelled", "Subscription Cancelled"),
                    ("appointment_booked", "Appointment Booked"),
                    ("newsletter_subscribed", "Newsletter Subscribed"),
                    ("newsletter_unsubscribed", "Newsletter Unsubscribed"),
                ],
                db_index=True,
                help_text="Type of event",
                max_length=40,
                verbose_name="event type",
            ),
        ),
    ]
