# Generated by Django 5.2.10 on 2026-01-27 05:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address for which OTP was generated",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="Hashed OTP code",
                        max_length=255,
                        verbose_name="OTP code hash",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup_verification", "Signup Verification"),
                            ("login_verification", "Login Verification"),
                            (
                                "password_reset_verification",
                                "Password Reset Verification",
                            ),
                        ],
                        db_index=True,
                        help_text="Purpose of this OTP (signup, login, or password reset)",
                        max_length=50,
                        verbose_name="OTP purpose",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this OTP has been successfully verified",
                        verbose_name="is verified",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when OTP was verified",
                        null=True,
                        verbose_name="verified at",
                    ),
                ),
                (
                    "attempts_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of verification attempts made",
                        verbose_name="attempts count",
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum number of verification attempts allowed",
                        verbose_name="max attempts",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Timestamp when OTP expires",
                        verbose_name="expires at",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which OTP was requested (for audit)",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent from which OTP was requested (for audit)",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this OTP (nullable until identity confirmed)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Verification",
                "verbose_name_plural": "OTP Verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "is_verified", "expires_at"],
                        name="accounts_ot_email_597fbe_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="accounts_ot_created_dffff8_idx"
                    ),
                ],
            },
        ),
    ]
