# Generated by Django 5.2.10 on 2026-03-07 09:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name",
                        max_length=150,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (auto-generated)",
                        max_length=170,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short description of the category",
                        verbose_name="description",
                    ),
                ),
                (
                    "svg_icon",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw SVG markup for the category icon. Use `currentColor` for fills/strokes so the icon inherits the surrounding text colour and adapts to dark/light mode.",
                        verbose_name="SVG icon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the category is publicly visible",
                        verbose_name="is active",
                    ),
                ),
                (
                    "requires_subscription",
                    models.BooleanField(
                        default=True,
                        help_text="If True, an active premium subscription grants access (subject to admin approval).",
                        verbose_name="requires subscription",
                    ),
                ),
                (
                    "is_purchasable",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to buy permanent access to this group.",
                        verbose_name="is purchasable",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="One-time price to unlock this group (if purchasable).",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="purchase price",
                    ),
                ),
                (
                    "purchase_currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD - US Dollar"),
                            ("EUR", "EUR - Euro"),
                            ("GBP", "GBP - British Pound"),
                            ("XAF", "XAF - CFA Franc"),
                            ("CAD", "CAD - Canadian Dollar"),
                        ],
                        default="USD",
                        help_text="Currency for the one-time purchase price.",
                        max_length=3,
                        verbose_name="purchase currency",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "requires_admin_approval",
                    models.BooleanField(
                        default=True,
                        help_text="If True, an admin must manually approve every access request (both subscription-based and purchase-based) before the user can participate. If False, a completed payment or valid subscription immediately grants access.",
                        verbose_name="requires admin approval",
                    ),
                ),
            ],
            options={
                "verbose_name": "forum category",
                "verbose_name_plural": "forum categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ForumThread",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date and time when the record was soft deleted",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Thread title", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Thread body (supports Markdown)",
                        verbose_name="content",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Pinned threads appear at the top of the category.",
                        verbose_name="is pinned",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Closed threads cannot receive new replies.",
                        verbose_name="is closed",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this thread has been viewed",
                        verbose_name="views count",
                    ),
                ),
                (
                    "votes_count",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Cached sum of up-votes minus down-votes cast directly on this thread (the opening question).  Updated atomically by ForumVote.",
                        verbose_name="votes count",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created the thread",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_threads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this thread belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="forums.forumcategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "forum thread",
                "verbose_name_plural": "forum threads",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadReply",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date and time when the record was soft deleted",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Reply body (supports Markdown)",
                        verbose_name="content",
                    ),
                ),
                (
                    "is_best_answer",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Marked by the thread author or an admin as the best answer. Best answers are displayed at the top.",
                        verbose_name="is best answer",
                    ),
                ),
                (
                    "votes_count",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Cached sum of up-votes minus down-votes",
                        verbose_name="votes count",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote the reply",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set this to turn the reply into a comment on another reply (level 2). Leave blank for a top-level answer (level 1).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="forums.threadreply",
                        verbose_name="parent reply",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="Thread this reply belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="forums.forumthread",
                        verbose_name="thread",
                    ),
                ),
            ],
            options={
                "verbose_name": "thread reply",
                "verbose_name_plural": "thread replies",
                "ordering": ["-is_best_answer", "-votes_count", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadAttachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached document or image",
                        upload_to="forums/attachments/%Y/%m/",
                        verbose_name="file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original name of the uploaded file",
                        max_length=255,
                        verbose_name="original filename",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent thread (leave blank if attached to a reply)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="forums.forumthread",
                        verbose_name="thread",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent reply (leave blank if attached to a thread)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="forums.threadreply",
                        verbose_name="reply",
                    ),
                ),
            ],
            options={
                "verbose_name": "thread attachment",
                "verbose_name_plural": "thread attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumVote",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(1, "Up-vote"), (-1, "Down-vote")],
                        help_text="1 = up-vote, -1 = down-vote",
                        verbose_name="value",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        help_text="Thread being voted on (set this OR reply, not both)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="forums.forumthread",
                        verbose_name="thread",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        help_text="User who cast the vote",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="voter",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reply being voted on (set this OR thread, not both)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="forums.threadreply",
                        verbose_name="reply",
                    ),
                ),
            ],
            options={
                "verbose_name": "forum vote",
                "verbose_name_plural": "forum votes",
            },
        ),
        migrations.CreateModel(
            name="ThreadReplyFeedback",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not helpful"),
                        ],
                        help_text="Was this answer helpful?",
                        max_length=20,
                        verbose_name="value",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional short comment explaining the feedback (e.g. 'Missing code example'). Not shown publicly.",
                        verbose_name="comment",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        help_text="The reply (best answer) being evaluated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="forums.threadreply",
                        verbose_name="reply",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who submitted the feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_reply_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "thread reply feedback",
                "verbose_name_plural": "thread reply feedbacks",
            },
        ),
        migrations.CreateModel(
            name="ForumGroupAccess",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Admin must approve before granting access (can be set to auto-approve via settings).",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("purchase", "One-time purchase"),
                        ],
                        default="purchase",
                        help_text="How the user obtained access.",
                        max_length=20,
                        verbose_name="access type",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("square", "Square"),
                        ],
                        default="",
                        help_text="Payment provider used for the purchase",
                        max_length=20,
                        verbose_name="payment provider",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("free_accepted", "Free (No Payment Required)"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Status of the payment transaction",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount paid for this access",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD - US Dollar"),
                            ("EUR", "EUR - Euro"),
                            ("GBP", "GBP - British Pound"),
                            ("XAF", "XAF - CFA Franc"),
                            ("CAD", "CAD - Canadian Dollar"),
                        ],
                        default="USD",
                        help_text="Currency of the payment",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe PaymentIntent ID, Flutterwave transaction ID, etc.",
                        max_length=160,
                        verbose_name="provider payment ID",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when an admin approved the access request",
                        null=True,
                        verbose_name="approved at",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional explanation provided by the admin when rejecting an access request. Displayed to the user.",
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved the access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Forum category purchased",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_accesses",
                        to="forums.forumcategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who purchased the group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_group_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "forum group access",
                "verbose_name_plural": "forum group accesses",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="forums_foru_user_id_b4a13e_idx"
                    )
                ],
                "unique_together": {("user", "category")},
            },
        ),
        migrations.AddIndex(
            model_name="forumthread",
            index=models.Index(
                fields=["category", "deleted_at"], name="forums_foru_categor_53c04b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="threadreply",
            index=models.Index(
                fields=["thread", "deleted_at"], name="forums_thre_thread__289d69_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="forumvote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reply__isnull", True), ("thread__isnull", False)),
                    models.Q(("reply__isnull", False), ("thread__isnull", True)),
                    _connector="OR",
                ),
                name="forums_vote_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="forumvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("thread__isnull", False)),
                fields=("thread", "voter"),
                name="forums_unique_thread_vote",
            ),
        ),
        migrations.AddConstraint(
            model_name="forumvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reply__isnull", False)),
                fields=("reply", "voter"),
                name="forums_unique_reply_vote",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="threadreplyfeedback",
            unique_together={("reply", "user")},
        ),
    ]
