# Generated by Django 5.2.10 on 2026-02-02 02:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterCampaign",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Campaign name", max_length=120, verbose_name="name"
                    ),
                ),
                (
                    "schedule_mode",
                    models.CharField(
                        choices=[
                            ("daily_5am", "Daily at 5 AM"),
                            ("every_5_days_5am", "Every 5 days at 5 AM"),
                            ("weekly_monday_5am", "Weekly on Monday at 5 AM"),
                            ("every_2_weeks_5am", "Every 2 weeks at 5 AM"),
                        ],
                        default="daily_5am",
                        help_text="Frequency and time for sending newsletters",
                        max_length=30,
                        verbose_name="schedule mode",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the campaign is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "template_subject",
                    models.CharField(
                        default="Article du jour",
                        help_text="Email subject template",
                        max_length=160,
                        verbose_name="template subject",
                    ),
                ),
                (
                    "template_body",
                    models.TextField(
                        default="",
                        help_text="Email body template (HTML)",
                        verbose_name="template body",
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last execution time of the campaign",
                        null=True,
                        verbose_name="last run at",
                    ),
                ),
            ],
            options={
                "verbose_name": "newsletter campaign",
                "verbose_name_plural": "newsletter campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of the recipient",
                        max_length=254,
                        verbose_name="recipient email",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject line",
                        max_length=200,
                        verbose_name="subject",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Current status of the email",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="ses",
                        help_text="Email service provider (SES, SendGrid, etc.)",
                        max_length=30,
                        verbose_name="provider",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Message ID from the provider",
                        max_length=180,
                        verbose_name="provider message ID",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if sending failed",
                        verbose_name="error message",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when the email was sent",
                        null=True,
                        verbose_name="sent at",
                    ),
                ),
            ],
            options={
                "verbose_name": "email log",
                "verbose_name_plural": "email logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_email", "status"],
                        name="newsletter__to_emai_3176ad_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="newsletter__status_3ab665_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Subscriber email address",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                        ],
                        db_index=True,
                        default="fr",
                        help_text="Preferred language for newsletters",
                        max_length=5,
                        verbose_name="language",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the subscription is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the email has been confirmed",
                        verbose_name="is confirmed",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time of email confirmation",
                        null=True,
                        verbose_name="confirmed at",
                    ),
                ),
                (
                    "unsub_token",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Token for unsubscribing without login",
                        max_length=64,
                        unique=True,
                        verbose_name="unsubscribe token",
                    ),
                ),
            ],
            options={
                "verbose_name": "newsletter subscriber",
                "verbose_name_plural": "newsletter subscribers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_confirmed"],
                        name="newsletter__is_acti_513949_idx",
                    )
                ],
            },
        ),
    ]
