# Generated by Django 5.2.10 on 2026-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="consent_given_at",
            field=models.DateTimeField(
                blank=True,
                help_text="GDPR: Date and time when user gave consent",
                null=True,
                verbose_name="consent given at",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="email_click_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of links clicked in emails",
                verbose_name="email click count",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="email_open_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of emails opened by subscriber",
                verbose_name="email open count",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address when subscriber signed up",
                null=True,
                verbose_name="IP address",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="last_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time of the last email sent",
                null=True,
                verbose_name="last email sent at",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("bounced", "Bounced"),
                ],
                db_index=True,
                default="active",
                help_text="Current status of the subscriber",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated tags for segmentation",
                max_length=500,
                verbose_name="tags",
            ),
        ),
    ]
