# Generated by Django 5.2.10 on 2026-02-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_newslettersubscriber_consent_given_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newslettersubscriber",
            name="status",
        ),
    ]
