# Generated by Django 5.2.10 on 2026-02-01 18:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name",
                        max_length=60,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier",
                        max_length=80,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name",
                        max_length=120,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier",
                        max_length=140,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Category description",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the category is visible",
                        verbose_name="is active",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order in listings",
                        verbose_name="sort order",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="content_cat_is_acti_59b16c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date and time when the content was published",
                        null=True,
                        verbose_name="published at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Article title", max_length=240, verbose_name="title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier",
                        max_length=260,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                        ],
                        db_index=True,
                        help_text="Article language",
                        max_length=5,
                        verbose_name="language",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("scheduled", "Scheduled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="beginner",
                        help_text="Content difficulty level",
                        max_length=20,
                        verbose_name="difficulty level",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid")],
                        db_index=True,
                        default="free",
                        help_text="Free or paid access",
                        max_length=10,
                        verbose_name="access type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Article price (if paid)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meta title for search engines",
                        max_length=70,
                        verbose_name="SEO title",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meta description for search engines",
                        max_length=160,
                        verbose_name="SEO description",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Canonical URL for duplicate content",
                        verbose_name="canonical URL",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Brief article summary",
                        verbose_name="summary",
                    ),
                ),
                (
                    "cover_image_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="S3 key/path for cover image (optimized)",
                        max_length=512,
                        verbose_name="cover image key",
                    ),
                ),
                (
                    "cover_alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alternative text for cover image",
                        max_length=180,
                        verbose_name="cover alt text",
                    ),
                ),
                (
                    "reading_time_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated reading time in minutes",
                        verbose_name="reading time (minutes)",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional YouTube video URL",
                        verbose_name="YouTube URL",
                    ),
                ),
                (
                    "youtube_start_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Start time in seconds for video preview",
                        verbose_name="YouTube start seconds",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Article author",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Article categories",
                        related_name="articles",
                        to="content.category",
                        verbose_name="categories",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Article tags",
                        related_name="articles",
                        to="content.tag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Page sequence number",
                        verbose_name="page number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Page section title",
                        max_length=240,
                        verbose_name="title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="URL-friendly identifier",
                        max_length=260,
                        verbose_name="slug",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Markdown/MDX formatted content",
                        verbose_name="content",
                    ),
                ),
                (
                    "toc_json",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Precomputed table of contents (JSON)",
                        verbose_name="table of contents",
                    ),
                ),
                (
                    "preview_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Content visible before paywall",
                        verbose_name="preview content",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Parent article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="content.article",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "article page",
                "verbose_name_plural": "article pages",
                "ordering": ["article", "page_number"],
                "indexes": [
                    models.Index(
                        fields=["article", "page_number"],
                        name="content_art_article_1a9d6a_idx",
                    )
                ],
                "unique_together": {("article", "page_number")},
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["language", "status", "access_type"],
                name="content_art_languag_ea6858_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "published_at"], name="content_art_status_4645e7_idx"
            ),
        ),
    ]
