# Generated by Django 5.2.10 on 2026-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="preview_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Content visible before paywall",
                verbose_name="preview content",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="toc_json",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Precomputed table of contents (JSON)",
                verbose_name="table of contents",
            ),
        ),
    ]
