# Generated by Django 5.2.10 on 2026-02-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_article_preview_content_article_toc_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="preview_content",
        ),
    ]
