# Generated by Django 5.2.10 on 2026-02-16 07:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_remove_articlepage_preview_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedArticles",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="First article to feature on homepage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.article",
                        verbose_name="first featured article",
                    ),
                ),
                (
                    "second_feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="Second article to feature on homepage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.article",
                        verbose_name="second featured article",
                    ),
                ),
                (
                    "third_feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="Third article to feature on homepage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.article",
                        verbose_name="third featured article",
                    ),
                ),
            ],
            options={
                "verbose_name": "featured articles",
                "verbose_name_plural": "featured articles",
            },
        ),
    ]
