# Generated by Django 5.2.10 on 2026-02-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_featuredarticles"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image for the article",
                null=True,
                upload_to="articles/covers/%Y/%m/",
                verbose_name="cover image",
            ),
        ),
        migrations.RemoveField(
            model_name="article",
            name="cover_image_key",
        ),
    ]
