# Generated by Django 5.2.10 on 2026-02-18 05:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_remove_article_cover_image_key_article_cover_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Session key for anonymous users",
                        max_length=40,
                        verbose_name="session key",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of claps (max 50 per user/session per article)",
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="count",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article being clapped",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claps",
                        to="content.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who clapped (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_claps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "clap",
                "verbose_name_plural": "claps",
                "unique_together": {("article", "user"), ("article", "session_key")},
                "indexes": [
                    models.Index(
                        fields=["article", "user"], name="content_cla_article_4d7a8e_idx"
                    ),
                    models.Index(
                        fields=["article", "session_key"],
                        name="content_cla_article_9e6f2b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "content",
                    models.TextField(help_text="Comment text", verbose_name="content"),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the comment has been edited",
                        verbose_name="is edited",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article being commented on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="content.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who wrote the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "-created_at"],
                        name="content_com_article_1a2b3c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article being liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="content.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who liked the article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "like",
                "verbose_name_plural": "likes",
                "unique_together": {("article", "user")},
                "indexes": [
                    models.Index(
                        fields=["article", "user"], name="content_lik_article_7c8d9e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        help_text="Comment being liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="content.comment",
                        verbose_name="comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who liked the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment like",
                "verbose_name_plural": "comment likes",
                "unique_together": {("comment", "user")},
                "indexes": [
                    models.Index(
                        fields=["comment", "user"], name="content_com_comment_1f2e3d_idx"
                    ),
                ],
            },
        ),
    ]
