# Generated by Django 5.2.10 on 2026-02-21 22:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_comment_commentlike_like_clap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableOfContents",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "structure",
                    models.JSONField(
                        default=list,
                        help_text="Hierarchical structure of headings: [{id, text, level, children}, ...]",
                    ),
                ),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=True,
                        help_text="If True, TOC is automatically regenerated when content changes",
                        verbose_name="Auto-generated",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_of_contents",
                        to="content.article",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table of Contents",
                "verbose_name_plural": "Tables of Contents",
                "ordering": ["article__title"],
            },
        ),
    ]
