# Generated by Django 5.2.10 on 2026-02-28 08:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseTag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name",
                        max_length=60,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier",
                        max_length=80,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "course tag",
                "verbose_name_plural": "course tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English"), ("es", "Español")],
                db_index=True,
                default="en",
                help_text="Course language",
                max_length=5,
                verbose_name="language",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Course tags / keywords",
                related_name="courses",
                to="content.coursetag",
                verbose_name="tags",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["language", "is_active"], name="content_cou_languag_29f0b5_idx"
            ),
        ),
    ]
