# Generated by Django 5.2.10 on 2026-02-02 01:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the resource document",
                        max_length=240,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the resource",
                        verbose_name="description",
                    ),
                ),
                (
                    "file_key",
                    models.CharField(
                        db_index=True,
                        help_text="S3 key/path to the document file",
                        max_length=512,
                        verbose_name="file key",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("purchase_required", "Purchase Required"),
                        ],
                        db_index=True,
                        default="premium",
                        help_text="Access level required to view this resource",
                        max_length=30,
                        verbose_name="access level",
                    ),
                ),
                (
                    "watermark_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable watermark on document",
                        verbose_name="watermark enabled",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated article",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="content.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="content.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "resource document",
                "verbose_name_plural": "resource documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["access_level", "created_at"],
                        name="resources_r_access__1928f2_idx",
                    )
                ],
            },
        ),
    ]
