# Generated by Django 5.2.10 on 2026-02-10 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcedocument",
            name="content_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MIME type of the file",
                max_length=100,
                verbose_name="content type",
            ),
        ),
        migrations.AddField(
            model_name="resourcedocument",
            name="download_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times downloaded",
                verbose_name="download count",
            ),
        ),
        migrations.AddField(
            model_name="resourcedocument",
            name="file_name",
            field=models.CharField(
                default=None,
                help_text="Original file name",
                max_length=255,
                verbose_name="file name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcedocument",
            name="file_size",
            field=models.BigIntegerField(
                default=0, help_text="File size in bytes", verbose_name="file size"
            ),
        ),
        migrations.AddField(
            model_name="resourcedocument",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether the resource is available",
                verbose_name="is active",
            ),
        ),
        migrations.AddField(
            model_name="resourcedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the resource",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_resources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcedocument",
            index=models.Index(
                fields=["article", "is_active"], name="resources_r_article_d6ce22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcedocument",
            index=models.Index(
                fields=["category", "is_active"], name="resources_r_categor_06fabe_idx"
            ),
        ),
    ]
