# Generated by Django 5.2.10 on 2026-02-02 02:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Coupon code",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("amount", "Fixed Amount")],
                        help_text="Discount type (percentage or fixed amount)",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "value_percent",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Discount percentage (1-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="percentage value",
                    ),
                ),
                (
                    "value_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed discount amount",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="fixed amount value",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum times the coupon can be used",
                        null=True,
                        verbose_name="max uses",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current usage count",
                        verbose_name="used count",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Coupon expiration date and time",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the coupon is currently active",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "coupon",
                "verbose_name_plural": "coupons",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="billing_cou_code_ea633c_idx"
                    ),
                    models.Index(
                        fields=["expires_at", "is_active"],
                        name="billing_cou_expires_6b5526_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Plan name",
                        max_length=100,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier",
                        max_length=120,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the plan is available for purchase",
                        verbose_name="is active",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Plan price",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("week", "Weekly"),
                            ("month", "Monthly"),
                            ("year", "Yearly"),
                        ],
                        default="month",
                        help_text="Billing period (monthly, yearly, etc.)",
                        max_length=10,
                        verbose_name="billing interval",
                    ),
                ),
                (
                    "features_json",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Plan features in JSON format",
                        verbose_name="features",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("square", "Square"),
                        ],
                        default="stripe",
                        help_text="Payment service provider",
                        max_length=20,
                        verbose_name="payment provider",
                    ),
                ),
                (
                    "provider_price_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe Price ID, PayPal plan ID, etc.",
                        max_length=160,
                        verbose_name="provider price ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "plans",
                "ordering": ["price"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "price"],
                        name="billing_pla_is_acti_28a1ac_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("square", "Square"),
                        ],
                        help_text="Payment service provider",
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Purchase amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe PaymentIntent ID, PayPal order ID, etc.",
                        max_length=160,
                        verbose_name="provider payment ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Purchased article",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="content.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Purchasing user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase",
                "verbose_name_plural": "purchases",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="billing_pur_user_id_81f148_idx"
                    )
                ],
                "unique_together": {("user", "article")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("square", "Square"),
                        ],
                        help_text="Payment service provider",
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "provider_subscription_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External subscription ID (Stripe, PayPal, etc.)",
                        max_length=160,
                        verbose_name="provider subscription ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Subscription payment status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of current billing period",
                        null=True,
                        verbose_name="current period start",
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="End of current billing period",
                        null=True,
                        verbose_name="current period end",
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="Cancel subscription at the end of period",
                        verbose_name="cancel at period end",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Subscribed plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                        verbose_name="plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Subscribed user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "indexes": [
                    models.Index(
                        fields=["user", "status", "current_period_end"],
                        name="billing_sub_user_id_3ed20e_idx",
                    )
                ],
            },
        ),
    ]
