# Generated by Django 5.2.11 on 2026-02-23 03:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_planfeature_planhistory_alter_plan_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('square', 'Square')], help_text='Payment provider (stripe, paypal, ...)', max_length=20, verbose_name='provider')),
                ('kind', models.CharField(default='one_time', help_text='Type of transaction (one_time, subscription, refund, invoice)', max_length=20, verbose_name='kind')),
                ('provider_payment_id', models.CharField(blank=True, default='', help_text='Provider payment identifier (PaymentIntent, Order, etc.)', max_length=160, verbose_name='provider payment ID')),
                ('provider_subscription_id', models.CharField(blank=True, default='', help_text='Provider subscription identifier (if applicable)', max_length=160, verbose_name='provider subscription ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Transaction amount (may be null for non-financial events)', max_digits=10, null=True, verbose_name='amount')),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Transaction status', max_length=20, verbose_name='status')),
                ('object_id', models.CharField(blank=True, default='', help_text='Related object id', max_length=36, verbose_name='object id')),
                ('idempotency_key', models.CharField(blank=True, default='', help_text='Provider idempotency key / local id for deduplication', max_length=160, verbose_name='idempotency key')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of attempts for this transaction', verbose_name='attempt count')),
                ('webhook_processed', models.BooleanField(default=False, help_text='Whether this transaction was processed from a webhook', verbose_name='webhook processed')),
                ('error_message', models.TextField(blank=True, default='', help_text='Provider error message or last failure reason', verbose_name='error message')),
                ('raw_response', models.JSONField(blank=True, help_text='Raw provider payload / response for debug and reconciliation', null=True, verbose_name='raw response')),
                ('content_type', models.ForeignKey(blank=True, help_text='Related object content type (Purchase or Subscription)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_payment_id'], name='billing_pay_provide_af8593_idx'), models.Index(fields=['provider', 'provider_subscription_id'], name='billing_pay_provide_7b5b38_idx'), models.Index(fields=['idempotency_key'], name='billing_pay_idempot_8e3136_idx'), models.Index(fields=['status', 'created_at'], name='billing_pay_status_271ed9_idx')],
            },
        ),
    ]
