# Generated by Django 5.2.10 on 2026-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_paymenttransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="pricing_discount",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Optional discount label, e.g. 20",
                verbose_name="pricing discount",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound"),
                    ("XAF", "XAF - CFA Franc"),
                    ("CAD", "CAD - Canadian Dollar"),
                ],
                default="USD",
                help_text="Currency code (ISO 4217)",
                max_length=3,
                verbose_name="currency",
            ),
        ),
    ]
