# Generated by Django 5.2.11 on 2026-02-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_pricing_discount_alter_plan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('free_accepted', 'Free (No Payment Required)')], db_index=True, default='pending', help_text='Transaction status', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('free_accepted', 'Free (No Payment Required)')], db_index=True, default='pending', help_text='Payment status', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('free_accepted', 'Free (No Payment Required)')], db_index=True, default='pending', help_text='Subscription payment status', max_length=20, verbose_name='status'),
        ),
    ]
