# Generated by Django 5.2.10 on 2026-02-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_paymenttransaction_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound"),
                    ("XAF", "XAF - CFA Franc"),
                    ("CAD", "CAD - Canadian Dollar"),
                ],
                default="USD",
                help_text="Currency code (ISO 4217)",
                max_length=3,
                verbose_name="currency",
            ),
        ),
    ]
