# Generated by Django 5.2.10 on 2026-02-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_merge_20260224_1557"),
        ("billing", "0006_alter_paymenttransaction_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated appointment (for appointment payment flows)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="appointments.appointment",
                verbose_name="appointment",
            ),
        ),
    ]
