# Generated by Django 5.2.10 on 2026-02-02 02:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Appointment type name",
                        max_length=120,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this type is available for booking",
                        verbose_name="is active",
                    ),
                ),
                (
                    "base_hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base hourly rate for this appointment type",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="base hourly rate",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "allowed_durations_minutes",
                    models.CharField(
                        default="30,60,90",
                        help_text="Comma-separated list of allowed durations",
                        max_length=60,
                        verbose_name="allowed durations (minutes)",
                    ),
                ),
                (
                    "pricing_rules_json",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JSON rules for dynamic pricing (urgency/weekend/complexity)",
                        verbose_name="pricing rules",
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment type",
                "verbose_name_plural": "appointment types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        db_index=True,
                        help_text="Day of week",
                        max_length=5,
                        verbose_name="weekday",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Availability start time", verbose_name="start time"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Availability end time", verbose_name="end time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this rule is active",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "availability rule",
                "verbose_name_plural": "availability rules",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Appointment start date and time",
                        verbose_name="start time",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Appointment end date and time",
                        verbose_name="end time",
                    ),
                ),
                (
                    "is_booked",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the slot has been booked",
                        verbose_name="is booked",
                    ),
                ),
                (
                    "booked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the slot was booked",
                        null=True,
                        verbose_name="booked at",
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment slot",
                "verbose_name_plural": "appointment slots",
                "ordering": ["start_at"],
                "indexes": [
                    models.Index(
                        fields=["start_at", "is_booked"],
                        name="appointment_start_a_872c6f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Appointment status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Appointment duration in minutes",
                        verbose_name="duration (minutes)",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Applied hourly rate",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="hourly rate",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total appointment cost",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="total amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("square", "Square"),
                        ],
                        default="stripe",
                        help_text="Payment service provider",
                        max_length=20,
                        verbose_name="payment provider",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External payment ID",
                        max_length=160,
                        verbose_name="provider payment ID",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Video conference or meeting URL",
                        verbose_name="meeting link",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes or instructions",
                        verbose_name="notes",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Appointment confirmation date/time",
                        null=True,
                        verbose_name="confirmed at",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Appointment cancellation date/time",
                        null=True,
                        verbose_name="cancelled at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Appointment user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        help_text="Associated time slot",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment",
                        to="appointments.appointmentslot",
                        verbose_name="slot",
                    ),
                ),
                (
                    "appointment_type",
                    models.ForeignKey(
                        help_text="Appointment type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointments.appointmenttype",
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment",
                "verbose_name_plural": "appointments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "payment_status"],
                        name="appointment_user_id_96af53_idx",
                    )
                ],
            },
        ),
    ]
