# Generated by Django 5.2.11 on 2026-02-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('free_accepted', 'Free (No Payment Required)')], db_index=True, default='pending', help_text='Payment status', max_length=20, verbose_name='payment status'),
        ),
    ]
