# Generated by Django 5.2.10 on 2026-02-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("link_pending", "Link Pending"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                    ("rescheduled", "Rescheduled"),
                ],
                db_index=True,
                default="pending",
                help_text="Appointment status",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
