# Generated by Django 5.2.10 on 2026-02-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone name shown on the public booking page (e.g. Africa/Douala)",
                        max_length=64,
                        verbose_name="display timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment settings",
                "verbose_name_plural": "appointment settings",
            },
        ),
    ]
