# Generated by Django 5.2.10 on 2026-02-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_payment_status"),
        ("appointments", "0003_add_appointment_settings"),
    ]

    operations = []
